#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Dec 10 20:13:09 CET 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 9945074be51d4a5aa8bc75b6a9d7fb69 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Orchestrator_behav xil_defaultlib.Orchestrator -log elaborate.log"
xelab -wto 9945074be51d4a5aa8bc75b6a9d7fb69 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Orchestrator_behav xil_defaultlib.Orchestrator -log elaborate.log

